// <auto-generated />
using DesktopCany.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesktopCany.Migrations
{
    [DbContext(typeof(CanyContext))]
    partial class CanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesktopCany.Entidades.BibliotecaEnt", b =>
                {
                    b.Property<long>("ID_Biblioteca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Biblioteca"));

                    b.Property<string>("Biblioteca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DescricaoLib")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ID_FcnModData")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ID_Linguagem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Biblioteca");

                    b.HasIndex("ID_FcnModData");

                    b.HasIndex("ID_Linguagem");

                    b.ToTable("TB_Bibliotecas");
                });

            modelBuilder.Entity("DesktopCany.Entidades.FuncaoEnt", b =>
                {
                    b.Property<string>("ID_FcnModData")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescricaoFcn")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ModEstavel")
                        .HasColumnType("bit");

                    b.Property<string>("ModProgramador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_FcnModData");

                    b.ToTable("TB_Funcoes");
                });

            modelBuilder.Entity("DesktopCany.Entidades.LinguagemEnt", b =>
                {
                    b.Property<string>("ID_Linguagem")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DescricaoLang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID_Linguagem");

                    b.ToTable("TB_Linguagens");
                });

            modelBuilder.Entity("DesktopCany.Entidades.BibliotecaEnt", b =>
                {
                    b.HasOne("DesktopCany.Entidades.FuncaoEnt", "FK_ID_FcnModData")
                        .WithMany()
                        .HasForeignKey("ID_FcnModData")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopCany.Entidades.LinguagemEnt", "FK_ID_Linguagem")
                        .WithMany()
                        .HasForeignKey("ID_Linguagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FK_ID_FcnModData");

                    b.Navigation("FK_ID_Linguagem");
                });
#pragma warning restore 612, 618
        }
    }
}
